#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tutorial06_AddRealtimeUpdates.Resource", IsApplication=true)]

namespace Tutorial06_AddRealtimeUpdates
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000d
			public const int axisBandsColor = 2130771981;
			
			// aapt resource value: 0x7f010016
			public const int axisTooltipBackground = 2130771990;
			
			// aapt resource value: 0x7f010014
			public const int axisTooltipTextColor = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int axisTooltipTextSize = 2130771989;
			
			// aapt resource value: 0x7f010024
			public const int bandFillDownColor = 2130772004;
			
			// aapt resource value: 0x7f010023
			public const int bandFillUpColor = 2130772003;
			
			// aapt resource value: 0x7f010022
			public const int bandStrokeDownColor = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int bandStrokeUpColor = 2130772001;
			
			// aapt resource value: 0x7f010020
			public const int candleStickFillDownColor = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public const int candleStickFillUpColor = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int candleStickStrokeDownColor = 2130771998;
			
			// aapt resource value: 0x7f01001d
			public const int candleStickStrokeUpColor = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int columnFillColor = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int columnLineColor = 2130771995;
			
			// aapt resource value: 0x7f010011
			public const int cursorLineColor = 2130771985;
			
			// aapt resource value: 0x7f01002b
			public const int defaultAnnotationGripsBackgroundColor = 2130772011;
			
			// aapt resource value: 0x7f01002a
			public const int defaultAnnotationGripsStrokeColor = 2130772010;
			
			// aapt resource value: 0x7f010006
			public const int defaultTextColor = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int defaultTextSize = 2130771973;
			
			// aapt resource value: 0x7f010017
			public const int labelBackground = 2130771991;
			
			// aapt resource value: 0x7f010004
			public const int legendBackground = 2130771972;
			
			// aapt resource value: 0x7f010025
			public const int lineAnnotationLineColor = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int lineAnnotationLineThickness = 2130772006;
			
			// aapt resource value: 0x7f01001a
			public const int lineSeriesColor = 2130771994;
			
			// aapt resource value: 0x7f01000b
			public const int majorGridLinesColor = 2130771979;
			
			// aapt resource value: 0x7f01000f
			public const int majorTickLinesLength = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int minorGridLinesColor = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int minorTickLinesLength = 2130771982;
			
			// aapt resource value: 0x7f010019
			public const int mountainAreaColor = 2130771993;
			
			// aapt resource value: 0x7f010018
			public const int mountainLineColor = 2130771992;
			
			// aapt resource value: 0x7f010002
			public const int renderableSeriesAreaBorderColor = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int renderableSeriesAreaFillColor = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int renderableSeriesAreaStrokeThickness = 2130771971;
			
			// aapt resource value: 0x7f010010
			public const int rolloverLineColor = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int rubberBandFillColor = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int rubberBandStrokeColor = 2130771986;
			
			// aapt resource value: 0x7f010000
			public const int sciChartBackground = 2130771968;
			
			// aapt resource value: 0x7f010028
			public const int textAnnotationBackgroundColor = 2130772008;
			
			// aapt resource value: 0x7f010027
			public const int textAnnotationTextColor = 2130772007;
			
			// aapt resource value: 0x7f010029
			public const int textAnnotationTextSize = 2130772009;
			
			// aapt resource value: 0x7f01000a
			public const int tickTextColor = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int tickTextSize = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int tickTextTypeFace = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int titleTextSize = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int legendItemCheckBoxNegativeMargin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int legendItemMargin = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int legendItemPointMarkerMargin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int legendItemPointMarkerWidth = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int legendItemSeriesNameLeftMargin = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int legendItemSeriesNameRightMargin = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int legendModifierPadding = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int legendTextSize = 2130968583;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int sci_chart_black_steel_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sci_chart_black_steel_label_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sci_chart_black_steel_legend_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sci_chart_bright_spark_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sci_chart_bright_spark_label_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sci_chart_bright_spark_legend_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sci_chart_chrome_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sci_chart_chrome_label_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sci_chart_chrome_legend_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sci_chart_electric_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sci_chart_electric_label_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sci_chart_electric_legend_background = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sci_chart_expression_dark_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sci_chart_expression_dark_label_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sci_chart_expression_dark_legend_background = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sci_chart_expression_light_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sci_chart_expression_light_label_background = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sci_chart_expression_light_legend_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sci_chart_oscilloscope_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int sci_chart_oscilloscope_label_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int sci_chart_oscilloscope_legend_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sci_chart_tooltip_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int sci_chart_v4_dark_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int sci_chart_v4_dark_label_background = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int sci_chart_v4_dark_legend_background = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int Chart = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int adornerLayer = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int annotationSurface = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int axisModifierSurfaceArea = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int chartModifierSurface = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int colorMapView = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int isVisible = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int listview = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int maximumTextView = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int middleTextView = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int minimumTextView = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int name = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int pointMarker = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int renderableSeriesArea = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int rotateLayout = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int text = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int axis_marker_annotation_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int legend_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int legend_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int scichart_default_cursor_modifier_tooltip_container = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int scichart_default_tooltip_modifier_tooltip_container = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int scichart_heatmap_colour_map_horizontal_layout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int scichart_heatmap_colour_map_vertical_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int scihart_surface_layout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int text_annotation_layout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int SciChart_BaseStyle = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int SciChart_BlackSteel = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int SciChart_Bright_Spark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int SciChart_ChromeStyle = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int SciChart_ElectricStyle = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int SciChart_ExpressionDarkStyle = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int SciChart_ExpressionLightStyle = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int SciChart_OscilloscopeStyle = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int SciChart_SciChartv4DarkStyle = 2131034120;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SciChartHeatmapColourMap = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int SciChartHeatmapColourMap_android_orientation = 0;
			
			public static int[] SciChartLegend = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int SciChartLegend_android_orientation = 0;
			
			public static int[] ThemeProvider = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011};
			
			// aapt resource value: 13
			public const int ThemeProvider_axisBandsColor = 13;
			
			// aapt resource value: 22
			public const int ThemeProvider_axisTooltipBackground = 22;
			
			// aapt resource value: 20
			public const int ThemeProvider_axisTooltipTextColor = 20;
			
			// aapt resource value: 21
			public const int ThemeProvider_axisTooltipTextSize = 21;
			
			// aapt resource value: 36
			public const int ThemeProvider_bandFillDownColor = 36;
			
			// aapt resource value: 35
			public const int ThemeProvider_bandFillUpColor = 35;
			
			// aapt resource value: 34
			public const int ThemeProvider_bandStrokeDownColor = 34;
			
			// aapt resource value: 33
			public const int ThemeProvider_bandStrokeUpColor = 33;
			
			// aapt resource value: 32
			public const int ThemeProvider_candleStickFillDownColor = 32;
			
			// aapt resource value: 31
			public const int ThemeProvider_candleStickFillUpColor = 31;
			
			// aapt resource value: 30
			public const int ThemeProvider_candleStickStrokeDownColor = 30;
			
			// aapt resource value: 29
			public const int ThemeProvider_candleStickStrokeUpColor = 29;
			
			// aapt resource value: 28
			public const int ThemeProvider_columnFillColor = 28;
			
			// aapt resource value: 27
			public const int ThemeProvider_columnLineColor = 27;
			
			// aapt resource value: 17
			public const int ThemeProvider_cursorLineColor = 17;
			
			// aapt resource value: 43
			public const int ThemeProvider_defaultAnnotationGripsBackgroundColor = 43;
			
			// aapt resource value: 42
			public const int ThemeProvider_defaultAnnotationGripsStrokeColor = 42;
			
			// aapt resource value: 6
			public const int ThemeProvider_defaultTextColor = 6;
			
			// aapt resource value: 5
			public const int ThemeProvider_defaultTextSize = 5;
			
			// aapt resource value: 23
			public const int ThemeProvider_labelBackground = 23;
			
			// aapt resource value: 4
			public const int ThemeProvider_legendBackground = 4;
			
			// aapt resource value: 37
			public const int ThemeProvider_lineAnnotationLineColor = 37;
			
			// aapt resource value: 38
			public const int ThemeProvider_lineAnnotationLineThickness = 38;
			
			// aapt resource value: 26
			public const int ThemeProvider_lineSeriesColor = 26;
			
			// aapt resource value: 11
			public const int ThemeProvider_majorGridLinesColor = 11;
			
			// aapt resource value: 15
			public const int ThemeProvider_majorTickLinesLength = 15;
			
			// aapt resource value: 12
			public const int ThemeProvider_minorGridLinesColor = 12;
			
			// aapt resource value: 14
			public const int ThemeProvider_minorTickLinesLength = 14;
			
			// aapt resource value: 25
			public const int ThemeProvider_mountainAreaColor = 25;
			
			// aapt resource value: 24
			public const int ThemeProvider_mountainLineColor = 24;
			
			// aapt resource value: 2
			public const int ThemeProvider_renderableSeriesAreaBorderColor = 2;
			
			// aapt resource value: 1
			public const int ThemeProvider_renderableSeriesAreaFillColor = 1;
			
			// aapt resource value: 3
			public const int ThemeProvider_renderableSeriesAreaStrokeThickness = 3;
			
			// aapt resource value: 16
			public const int ThemeProvider_rolloverLineColor = 16;
			
			// aapt resource value: 19
			public const int ThemeProvider_rubberBandFillColor = 19;
			
			// aapt resource value: 18
			public const int ThemeProvider_rubberBandStrokeColor = 18;
			
			// aapt resource value: 0
			public const int ThemeProvider_sciChartBackground = 0;
			
			// aapt resource value: 40
			public const int ThemeProvider_textAnnotationBackgroundColor = 40;
			
			// aapt resource value: 39
			public const int ThemeProvider_textAnnotationTextColor = 39;
			
			// aapt resource value: 41
			public const int ThemeProvider_textAnnotationTextSize = 41;
			
			// aapt resource value: 10
			public const int ThemeProvider_tickTextColor = 10;
			
			// aapt resource value: 7
			public const int ThemeProvider_tickTextSize = 7;
			
			// aapt resource value: 9
			public const int ThemeProvider_tickTextTypeFace = 9;
			
			// aapt resource value: 8
			public const int ThemeProvider_titleTextSize = 8;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
