#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tutorial04_AddZoomPan.Resource", IsApplication=true)]

namespace Tutorial04_AddZoomPan
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int axisBandsColor = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int axisTooltipBackground = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int axisTooltipTextColor = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int axisTooltipTextSize = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int bandFillDownColor = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int bandFillUpColor = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int bandStrokeDownColor = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int bandStrokeUpColor = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int candleStickFillDownColor = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int candleStickFillUpColor = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int candleStickStrokeDownColor = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int candleStickStrokeUpColor = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int columnFillColor = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int columnLineColor = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int cursorLineColor = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int defaultAnnotationGripsBackgroundColor = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int defaultAnnotationGripsStrokeColor = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int defaultPieSegmentTitleTextColor = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int defaultPieSegmentTitleTextSize = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int defaultTextColor = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int defaultTextSize = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int labelBackground = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int legendBackground = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int lineAnnotationLineColor = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int lineAnnotationLineThickness = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int lineSeriesColor = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int majorGridLinesColor = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int majorTickLinesLength = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int minorGridLinesColor = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int minorTickLinesLength = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int mountainAreaColor = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int mountainLineColor = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int renderableSeriesAreaBorderColor = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int renderableSeriesAreaFillColor = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int renderableSeriesAreaStrokeThickness = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int rolloverLineColor = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int rubberBandFillColor = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int rubberBandStrokeColor = 2130772005;
			
			// aapt resource value: 0x7F010026
			public const int sciChartBackground = 2130772006;
			
			// aapt resource value: 0x7F010027
			public const int textAnnotationBackgroundColor = 2130772007;
			
			// aapt resource value: 0x7F010028
			public const int textAnnotationTextColor = 2130772008;
			
			// aapt resource value: 0x7F010029
			public const int textAnnotationTextSize = 2130772009;
			
			// aapt resource value: 0x7F01002A
			public const int tickTextColor = 2130772010;
			
			// aapt resource value: 0x7F01002B
			public const int tickTextSize = 2130772011;
			
			// aapt resource value: 0x7F01002C
			public const int tickTextTypeFace = 2130772012;
			
			// aapt resource value: 0x7F01002D
			public const int titleTextSize = 2130772013;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int legendItemCheckBoxNegativeMargin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int legendItemMargin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int legendItemPointMarkerMargin = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int legendItemPointMarkerWidth = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int legendItemSeriesNameLeftMargin = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int legendItemSeriesNameRightMargin = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int legendModifierPadding = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int legendTextSize = 2130837511;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int sci_chart_black_steel_background = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int sci_chart_black_steel_label_background = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int sci_chart_black_steel_legend_background = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int sci_chart_bright_spark_background = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int sci_chart_bright_spark_label_background = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int sci_chart_bright_spark_legend_background = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int sci_chart_chrome_background = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int sci_chart_chrome_label_background = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int sci_chart_chrome_legend_background = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int sci_chart_electric_background = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int sci_chart_electric_label_background = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int sci_chart_electric_legend_background = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int sci_chart_expression_dark_background = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int sci_chart_expression_dark_label_background = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int sci_chart_expression_dark_legend_background = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int sci_chart_expression_light_background = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int sci_chart_expression_light_label_background = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int sci_chart_expression_light_legend_background = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int sci_chart_oscilloscope_background = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int sci_chart_oscilloscope_label_background = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int sci_chart_oscilloscope_legend_background = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int sci_chart_tooltip_background = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int sci_chart_v4_dark_background = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int sci_chart_v4_dark_label_background = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int sci_chart_v4_dark_legend_background = 2130903065;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040001
			public const int adornerLayer = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int annotationOverlaySurface = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int annotationUnderlaySurface = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int axisModifierSurfaceArea = 2130968580;
			
			// aapt resource value: 0x7F040000
			public const int Chart = 2130968576;
			
			// aapt resource value: 0x7F040005
			public const int chartModifierSurface = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int colorMapView = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int isVisible = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int maximumTextView = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int middleTextView = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int minimumTextView = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int name = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int pointMarker = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int renderableSeriesArea = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int rotateLayout = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int text = 2130968591;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int axis_marker_annotation_layout = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int horizontal_legend_placeholder_layout = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int legend_item = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int Main = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int scichart_default_cursor_modifier_tooltip_container = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int scichart_default_tooltip_modifier_tooltip_container = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int scichart_heatmap_colour_map_horizontal_layout = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int scichart_heatmap_colour_map_vertical_layout = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int scihart_surface_layout = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int text_annotation_layout = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int vertical_legend_placeholder_layout = 2131034122;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int SciChart_BaseStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int SciChart_BlackSteel = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int SciChart_Bright_Spark = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int SciChart_ChromeStyle = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int SciChart_ElectricStyle = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int SciChart_ExpressionDarkStyle = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int SciChart_ExpressionLightStyle = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int SciChart_OscilloscopeStyle = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int SciChart_SciChartv4DarkStyle = 2131099656;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10100C4 }
			public static int[] SciChartHeatmapColourMap = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int SciChartHeatmapColourMap_android_orientation = 0;
			
			// aapt resource value: { 0x10100C4 }
			public static int[] SciChartLegend = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int SciChartLegend_android_orientation = 0;
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011,0x7F010012,0x7F010013,0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010018,0x7F010019,0x7F01001A,0x7F01001B,0x7F01001C,0x7F01001D,0x7F01001E,0x7F01001F,0x7F010020,0x7F010021,0x7F010022,0x7F010023,0x7F010024,0x7F010025,0x7F010026,0x7F010027,0x7F010028,0x7F010029,0x7F01002A,0x7F01002B,0x7F01002C,0x7F01002D }
			public static int[] ThemeProvider = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013};
			
			// aapt resource value: 0
			public const int ThemeProvider_axisBandsColor = 0;
			
			// aapt resource value: 1
			public const int ThemeProvider_axisTooltipBackground = 1;
			
			// aapt resource value: 2
			public const int ThemeProvider_axisTooltipTextColor = 2;
			
			// aapt resource value: 3
			public const int ThemeProvider_axisTooltipTextSize = 3;
			
			// aapt resource value: 4
			public const int ThemeProvider_bandFillDownColor = 4;
			
			// aapt resource value: 5
			public const int ThemeProvider_bandFillUpColor = 5;
			
			// aapt resource value: 6
			public const int ThemeProvider_bandStrokeDownColor = 6;
			
			// aapt resource value: 7
			public const int ThemeProvider_bandStrokeUpColor = 7;
			
			// aapt resource value: 8
			public const int ThemeProvider_candleStickFillDownColor = 8;
			
			// aapt resource value: 9
			public const int ThemeProvider_candleStickFillUpColor = 9;
			
			// aapt resource value: 10
			public const int ThemeProvider_candleStickStrokeDownColor = 10;
			
			// aapt resource value: 11
			public const int ThemeProvider_candleStickStrokeUpColor = 11;
			
			// aapt resource value: 12
			public const int ThemeProvider_columnFillColor = 12;
			
			// aapt resource value: 13
			public const int ThemeProvider_columnLineColor = 13;
			
			// aapt resource value: 14
			public const int ThemeProvider_cursorLineColor = 14;
			
			// aapt resource value: 15
			public const int ThemeProvider_defaultAnnotationGripsBackgroundColor = 15;
			
			// aapt resource value: 16
			public const int ThemeProvider_defaultAnnotationGripsStrokeColor = 16;
			
			// aapt resource value: 17
			public const int ThemeProvider_defaultPieSegmentTitleTextColor = 17;
			
			// aapt resource value: 18
			public const int ThemeProvider_defaultPieSegmentTitleTextSize = 18;
			
			// aapt resource value: 19
			public const int ThemeProvider_defaultTextColor = 19;
			
			// aapt resource value: 20
			public const int ThemeProvider_defaultTextSize = 20;
			
			// aapt resource value: 21
			public const int ThemeProvider_labelBackground = 21;
			
			// aapt resource value: 22
			public const int ThemeProvider_legendBackground = 22;
			
			// aapt resource value: 23
			public const int ThemeProvider_lineAnnotationLineColor = 23;
			
			// aapt resource value: 24
			public const int ThemeProvider_lineAnnotationLineThickness = 24;
			
			// aapt resource value: 25
			public const int ThemeProvider_lineSeriesColor = 25;
			
			// aapt resource value: 26
			public const int ThemeProvider_majorGridLinesColor = 26;
			
			// aapt resource value: 27
			public const int ThemeProvider_majorTickLinesLength = 27;
			
			// aapt resource value: 28
			public const int ThemeProvider_minorGridLinesColor = 28;
			
			// aapt resource value: 29
			public const int ThemeProvider_minorTickLinesLength = 29;
			
			// aapt resource value: 30
			public const int ThemeProvider_mountainAreaColor = 30;
			
			// aapt resource value: 31
			public const int ThemeProvider_mountainLineColor = 31;
			
			// aapt resource value: 32
			public const int ThemeProvider_renderableSeriesAreaBorderColor = 32;
			
			// aapt resource value: 33
			public const int ThemeProvider_renderableSeriesAreaFillColor = 33;
			
			// aapt resource value: 34
			public const int ThemeProvider_renderableSeriesAreaStrokeThickness = 34;
			
			// aapt resource value: 35
			public const int ThemeProvider_rolloverLineColor = 35;
			
			// aapt resource value: 36
			public const int ThemeProvider_rubberBandFillColor = 36;
			
			// aapt resource value: 37
			public const int ThemeProvider_rubberBandStrokeColor = 37;
			
			// aapt resource value: 38
			public const int ThemeProvider_sciChartBackground = 38;
			
			// aapt resource value: 39
			public const int ThemeProvider_textAnnotationBackgroundColor = 39;
			
			// aapt resource value: 40
			public const int ThemeProvider_textAnnotationTextColor = 40;
			
			// aapt resource value: 41
			public const int ThemeProvider_textAnnotationTextSize = 41;
			
			// aapt resource value: 42
			public const int ThemeProvider_tickTextColor = 42;
			
			// aapt resource value: 43
			public const int ThemeProvider_tickTextSize = 43;
			
			// aapt resource value: 44
			public const int ThemeProvider_tickTextTypeFace = 44;
			
			// aapt resource value: 45
			public const int ThemeProvider_titleTextSize = 45;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
